const catQuestions = [
  { id: 1, dimension: "A/I", question: "How does your cat react when you return home?", options: [{ text: "Comes over quickly", value: "A" }, { text: "Checks you first", value: "A" }, { text: "Keeps its own rhythm", value: "I" }] },
  { id: 2, dimension: "A/I", question: "Where does your cat rest during quiet time?", options: [{ text: "Very close to people", value: "A" }, { text: "Same room, some distance", value: "A" }, { text: "Separate private spot", value: "I" }] },
  { id: 3, dimension: "A/I", question: "How does your cat respond when called?", options: [{ text: "Clearly turns or comes", value: "A" }, { text: "Looks, then decides", value: "I" }, { text: "Mostly ignores it", value: "I" }] },
  { id: 4, dimension: "A/I", question: "Where does your cat settle when you sit down?", options: [{ text: "On you or against you", value: "A" }, { text: "Nearby after checking", value: "A" }, { text: "Away from people", value: "I" }] },
  { id: 5, dimension: "A/I", question: "How does your cat react to visitors?", options: [{ text: "Visible and curious", value: "A" }, { text: "Observes from distance", value: "I" }, { text: "Hides until quiet", value: "I" }] },
  { id: 6, dimension: "A/I", question: "How much physical contact does your cat prefer?", options: [{ text: "Frequent contact", value: "A" }, { text: "Brief contact only", value: "I" }, { text: "Only on its terms", value: "I" }] },
  { id: 8, dimension: "A/I", question: "Where does your cat sleep or nap?", options: [{ text: "Close to people", value: "A" }, { text: "Starts close then moves", value: "A" }, { text: "Separate bed or corner", value: "I" }] },
  { id: 10, dimension: "E/S", question: "How does your cat react to a new object?", options: [{ text: "Investigates right away", value: "E" }, { text: "Studies before moving", value: "S" }, { text: "Avoids it for a while", value: "S" }] },
  { id: 11, dimension: "E/S", question: "How does your cat enter an unfamiliar space?", options: [{ text: "Explores quickly", value: "E" }, { text: "Moves slowly and checks", value: "S" }, { text: "Freezes or hides", value: "S" }] },
  { id: 12, dimension: "E/S", question: "How does your cat react when familiar items move?", options: [{ text: "Adapts soon", value: "E" }, { text: "Inspects carefully", value: "S" }, { text: "Prefers the old setup", value: "S" }] },
  { id: 13, dimension: "E/S", question: "How does your cat approach a new toy?", options: [{ text: "Touches it right away", value: "E" }, { text: "Sniffs first", value: "S" }, { text: "Waits until safe", value: "S" }] },
  { id: 14, dimension: "E/S", question: "How does your cat react to an unfamiliar sound?", options: [{ text: "Moves toward it", value: "E" }, { text: "Pauses and listens", value: "S" }, { text: "Retreats to safety", value: "S" }] },
  { id: 15, dimension: "E/S", question: "How predictable is your cat's routine?", options: [{ text: "Flexible and curious", value: "E" }, { text: "Mostly predictable", value: "S" }, { text: "Strongly fixed", value: "S" }] },
  { id: 18, dimension: "E/S", question: "How quickly does your cat recover after stress?", options: [{ text: "Quickly returns to normal", value: "E" }, { text: "Needs time to check", value: "S" }, { text: "Stays cautious for long", value: "S" }] },
  { id: 19, dimension: "V/C", question: "How does your cat show excitement before a meal?", options: [{ text: "Very visibly", value: "V" }, { text: "Moderately", value: "C" }, { text: "Very composed", value: "C" }] },
  { id: 20, dimension: "V/C", question: "How does your cat behave during active play?", options: [{ text: "Fast, repeated bursts", value: "V" }, { text: "Short controlled rounds", value: "C" }, { text: "Slow and gentle", value: "C" }] },
  { id: 21, dimension: "V/C", question: "How does your cat ask for something?", options: [{ text: "Clear vocal or body signals", value: "V" }, { text: "Small signals", value: "C" }, { text: "Waits quietly", value: "C" }] },
  { id: 22, dimension: "V/C", question: "How does your cat react to sudden movement?", options: [{ text: "Big visible reaction", value: "V" }, { text: "Checks then settles", value: "C" }, { text: "Very subtle reaction", value: "C" }] },
  { id: 23, dimension: "V/C", question: "How easy is it to read your cat's body language?", options: [{ text: "Very easy to read", value: "V" }, { text: "Moderately readable", value: "C" }, { text: "Mostly steady", value: "C" }] },
  { id: 24, dimension: "V/C", question: "How does your cat greet a favorite person?", options: [{ text: "Obvious excitement", value: "V" }, { text: "Quiet affection", value: "C" }, { text: "Calm acknowledgement", value: "C" }] },
  { id: 26, dimension: "V/C", question: "How does your cat behave when frustrated?", options: [{ text: "Shows it clearly", value: "V" }, { text: "Moves away quietly", value: "C" }, { text: "Disengages calmly", value: "C" }] },
  { id: 28, dimension: "P/G", question: "How does your cat move around the home?", options: [{ text: "Turns spaces into games", value: "P" }, { text: "Patrols familiar spots", value: "G" }, { text: "Watches from lookout spots", value: "G" }] },
  { id: 29, dimension: "P/G", question: "How does your cat react to an open door or window?", options: [{ text: "Treats it like play", value: "P" }, { text: "Inspects the boundary", value: "G" }, { text: "Watches from safe distance", value: "G" }] },
  { id: 31, dimension: "P/G", question: "What does your cat do when a toy is hidden?", options: [{ text: "Pounces and digs", value: "P" }, { text: "Searches methodically", value: "G" }, { text: "Watches before acting", value: "G" }] },
  { id: 32, dimension: "P/G", question: "How does your cat react to fast movement nearby?", options: [{ text: "Chases or swats", value: "P" }, { text: "Monitors movement", value: "G" }, { text: "Moves to guarded distance", value: "G" }] },
  { id: 33, dimension: "P/G", question: "What does your cat focus on when guests arrive?", options: [{ text: "Bags, shoes, strings, motion", value: "P" }, { text: "Scent marks and presence", value: "G" }, { text: "Hidden observation", value: "G" }] },
  { id: 34, dimension: "P/G", question: "How does your cat respond when you start a game?", options: [{ text: "Responds quickly", value: "P" }, { text: "Plays briefly then watches", value: "G" }, { text: "Prefers observing first", value: "G" }] },
  { id: 36, dimension: "P/G", question: "How does your cat react to a small moving object?", options: [{ text: "Stalks and pounces", value: "P" }, { text: "Tracks carefully", value: "G" }, { text: "Waits until safe", value: "G" }] },
];

const dogQuestions = [
  { id: 1, dimension: "A/I", question: "How does your dog react when you return home?", options: [{ text: "Very close greeting", value: "A" }, { text: "Checks in then settles", value: "A" }, { text: "Keeps doing its own thing", value: "I" }] },
  { id: 2, dimension: "A/I", question: "What does your dog do when you change rooms?", options: [{ text: "Follows closely", value: "A" }, { text: "Checks your location", value: "A" }, { text: "Stays comfortable where it is", value: "I" }] },
  { id: 3, dimension: "A/I", question: "Where does your dog rest during quiet time?", options: [{ text: "Very close to people", value: "A" }, { text: "Same room with some space", value: "A" }, { text: "Separate bed or corner", value: "I" }] },
  { id: 4, dimension: "A/I", question: "How does your dog respond when called?", options: [{ text: "Turns and comes quickly", value: "A" }, { text: "Looks back then decides", value: "I" }, { text: "Responds if worthwhile", value: "I" }] },
  { id: 5, dimension: "A/I", question: "How does your dog behave when briefly left alone?", options: [{ text: "Waits for your return", value: "A" }, { text: "Settles after checking", value: "A" }, { text: "Continues independent routine", value: "I" }] },
  { id: 6, dimension: "A/I", question: "How much contact does your dog seek?", options: [{ text: "Seeks a lot of contact", value: "A" }, { text: "Accepts briefly then leaves", value: "I" }, { text: "Prefers to initiate", value: "I" }] },
  { id: 8, dimension: "A/I", question: "How often does your dog check on you during walks?", options: [{ text: "Very often", value: "A" }, { text: "Sometimes while exploring", value: "A" }, { text: "Focuses on its own route", value: "I" }] },
  { id: 10, dimension: "E/S", question: "How does your dog explore a new outdoor area?", options: [{ text: "Moves forward right away", value: "E" }, { text: "Studies before moving", value: "S" }, { text: "Needs time to relax", value: "S" }] },
  { id: 11, dimension: "E/S", question: "How does your dog approach unfamiliar people?", options: [{ text: "Curious and friendly", value: "E" }, { text: "Watches body language first", value: "S" }, { text: "Keeps distance", value: "S" }] },
  { id: 12, dimension: "E/S", question: "How does your dog react to a different walking route?", options: [{ text: "Enjoys the new smells", value: "E" }, { text: "Pauses often to understand", value: "S" }, { text: "Prefers the known path", value: "S" }] },
  { id: 13, dimension: "E/S", question: "How does your dog approach a new object?", options: [{ text: "Uses it right away", value: "E" }, { text: "Sniffs and tests it", value: "S" }, { text: "Waits until familiar", value: "S" }] },
  { id: 14, dimension: "E/S", question: "How does your dog react when familiar items move?", options: [{ text: "Adapts quickly", value: "E" }, { text: "Inspects carefully", value: "S" }, { text: "Prefers the old arrangement", value: "S" }] },
  { id: 15, dimension: "E/S", question: "How does your dog react to an unfamiliar sound?", options: [{ text: "Moves toward it", value: "E" }, { text: "Stops and scans", value: "S" }, { text: "Retreats or barks from safety", value: "S" }] },
  { id: 18, dimension: "E/S", question: "How quickly does your dog recover after being startled?", options: [{ text: "Very quickly", value: "E" }, { text: "Needs a few minutes", value: "S" }, { text: "Remains cautious", value: "S" }] },
  { id: 19, dimension: "V/C", question: "How does your dog show excitement when greeting someone?", options: [{ text: "Big visible energy", value: "V" }, { text: "Warm then settles", value: "C" }, { text: "Quiet attention", value: "C" }] },
  { id: 20, dimension: "V/C", question: "How does your dog behave during active play?", options: [{ text: "Fast and intense", value: "V" }, { text: "Controlled rounds", value: "C" }, { text: "Gentle or short play", value: "C" }] },
  { id: 21, dimension: "V/C", question: "How does your dog ask for something?", options: [{ text: "Obvious repeated signals", value: "V" }, { text: "Small hints", value: "C" }, { text: "Waits quietly", value: "C" }] },
  { id: 22, dimension: "V/C", question: "How does your dog react to sudden movement?", options: [{ text: "Strong visible reaction", value: "V" }, { text: "Checks and settles", value: "C" }, { text: "Small pause only", value: "C" }] },
  { id: 23, dimension: "V/C", question: "How easy is it to read your dog's emotions?", options: [{ text: "Very visible", value: "V" }, { text: "Moderate", value: "C" }, { text: "Subtle and controlled", value: "C" }] },
  { id: 24, dimension: "V/C", question: "How does your dog behave while waiting for a walk or meal?", options: [{ text: "Strong anticipation", value: "V" }, { text: "Some excitement", value: "C" }, { text: "Stays composed", value: "C" }] },
  { id: 26, dimension: "V/C", question: "During high-energy moments, your dog:", options: [{ text: "Runs or jumps a lot", value: "V" }, { text: "Has bursts then slows", value: "C" }, { text: "Keeps a steady pace", value: "C" }] },
  { id: 28, dimension: "P/G", question: "What does your dog focus on while at home?", options: [{ text: "Games and interaction", value: "P" }, { text: "Entrances and sounds", value: "G" }, { text: "Watching the household", value: "G" }] },
  { id: 29, dimension: "P/G", question: "How does your dog react when someone passes the home?", options: [{ text: "Excited playful energy", value: "P" }, { text: "Alerts and checks", value: "G" }, { text: "Keeps a steady watch", value: "G" }] },
  { id: 31, dimension: "P/G", question: "What does your dog do when people move around the home?", options: [{ text: "Joins the activity", value: "P" }, { text: "Tracks what is happening", value: "G" }, { text: "Observes from a spot", value: "G" }] },
  { id: 32, dimension: "P/G", question: "How does your dog react to unfamiliar animals or people?", options: [{ text: "Playful greeting", value: "P" }, { text: "Assesses distance and posture", value: "G" }, { text: "Guarded position", value: "G" }] },
  { id: 33, dimension: "P/G", question: "How does your dog approach a food puzzle or scent game?", options: [{ text: "Treats it like a fun game", value: "P" }, { text: "Works methodically", value: "G" }, { text: "Solves carefully", value: "G" }] },
  { id: 34, dimension: "P/G", question: "What does your dog do when something unusual happens?", options: [{ text: "Turns it into movement and curiosity", value: "P" }, { text: "Checks and monitors it", value: "G" }, { text: "Keeps watch until stable", value: "G" }] },
  { id: 36, dimension: "P/G", question: "What role does your dog usually take at home?", options: [{ text: "Play initiator", value: "P" }, { text: "Alert observer", value: "G" }, { text: "Quiet guardian", value: "G" }] },
];

function getQuestions(species) {
  return species === "dog" ? dogQuestions : catQuestions;
}

module.exports = {
  catQuestions,
  dogQuestions,
  getQuestions,
};
